name: Tests

on:
  push:
  pull_request:

jobs:
  package-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install .
      - run: rotatepdf --help
